services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: on-failure
    container_name: messenger
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      CORS_ALLOW_ORIGIN_LIST: ${CORS_ALLOW_ORIGIN_LIST}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:16.8
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
