"""Chat Messsage Group User

Revision ID: 1cf0bd32aa4e
Revises:
Create Date: 2025-04-03 17:07:27.116236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str | None = "1cf0bd32aa4e"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "chat_type",
            sa.Enum("public", "private", name="chattypeenum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("chats_pkey")),
        sa.UniqueConstraint("name", name=op.f("chats_name_key")),
    )
    op.create_index(op.f("chats_id_idx"), "chats", ["id"], unique=False)
    op.create_table(
        "chats_participants",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "chat_id", "participant_id", name=op.f("chats_participants_pkey")
        ),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_index(op.f("users_id_idx"), "users", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("was_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("messages_chat_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("messages_sender_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index(op.f("messages_id_idx"), "messages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("messages_id_idx"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("users_id_idx"), table_name="users")
    op.drop_table("users")
    op.drop_table("chats_participants")
    op.drop_index(op.f("chats_id_idx"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
